image: amazoncorretto:11

stages:
  - build
  - test

before_script:
  - cd team2_project
  - echo `pwd`
  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE"
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew check

after_script:
  - echo "[CI] Done"
  - cat /builds/team2/team2/team2_project/build/reports/tests/test/index.html #debug
