image: amazoncorretto:11

stages:
  - build
  - test

before_script:
  - cd team2_project
  - echo `pwd`
  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE"
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - team2_project/.gradle/wrapper
    - team2_project/.gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - team2_project/build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew check
  artifacts:
    when: always
    reports:
      junit: team2_project/build/test-results/test/**/TEST-*.xml

after_script:
  - echo "[CI] Done"
